Repository webapp-suite/ui, pull requests merged in 2019-09, with the labels that each got.

#56 build(webpack): update webpack to webpack@4.39.3
  .babelrc
  config/postcss.config.js
  config/webpack.config.js
  config/webpack.config.site.js
  package-lock.json
  package.json
  scripts/create.js
  scripts/deploy.js
  scripts/template/dox.js
  scripts/template/index.js
  scripts/template/index.less
  site/apps/Start/index.js
  site/index.html
  site/server.js
Labels: PR: build

#58 build(webpack): disable webpack minification cuz of prod issue
  config/webpack.config.site.js
Labels: PR: build

#67 chore(scripts): optmize npm run create script
  scripts/create.js
  scripts/template/dox.js
  src/components/index.js
Labels: PR: chore

#69 build(npmdeps): upgrade npm dependencies
  jest.config.json
  package-lock.json
  package.json
Labels: PR: build

#68 chore(site): fix long code display issue
  site/widgets/Layout/index.less
Labels: PR: chore

#75 ci(travis): add fossa in ci and update readme
  .nvmrc
  .travis.yml
  README.md
  package-lock.json
Labels: PR: ci

#71 build(webpacksite): fix css missing in site prod mode
  .travis.yml
  config/webpack.config.js
  config/webpack.config.site.js
  package.json
  site/index.html
Labels: PR: build

#76 feat(button): add loading attribute to button to initialize a spinner
  .eslintignore
  .prettierignore
  site/3rdParty/react-dom/react-dom.development.js
  site/3rdParty/react-dom/react-dom.production.min.js
  site/3rdParty/react/react.development.js
  site/3rdParty/react/react.production.min.js
  site/widgets/Doc/index.less
  src/components/Button/__tests__/index.test.js
  src/components/Button/docs/Button.dox
  src/components/Button/index.js
  src/components/Button/index.less
Labels: PR: feat
